my_project:
  target: dev
  outputs:
    dev:
      dbname: new_sample_db
      host: localhost
      pass: sample_password
      port: 5432
      schema: dev
      threads: 1
      type: postgres
      user: sample_user

    prod:
      dbname: new_sample_db
      host: localhost
      pass: sample_password
      port: 5432
      schema: prod
      threads: 1
      type: postgres
      user: sample_user
